name: Emit Webhook

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]

jobs:
  emit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Emit Webhook
        run: |
          curl -X POST https://9d5f581e-c570-4717-bc1a-95a36a90e932-00-1xcajxkbt1emi.sisko.replit.dev/
          -H "Content-Type: application/json" \
          -d '{
            "request_id": "${{ github.sha }}",
            "author": "${{ github.actor }}",
            "action": "${{ github.event_name }}",
            "from_branch": "main",
            "to_branch": "main"
          }'
