name: Emit Webhook

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, closed]

jobs:
  emit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Emit Webhook
        run: |
          curl -X POST https://python-template--shimpisharma2001.repl.co/webhook

          -H "Content-Type: application/json" \
          -d '{"request_id": "'"${{ github.sha }}"'", "author": "'"${{ github.actor }}"'", "action": "'"${{ github.event_name }}"'", "from_branch": "main", "to_branch": "main"}'
      
