name: Emit Webhook

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, closed ]

jobs:
  emit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Webhook
        run: |
          # detect event type & branches
          EVENT="${GITHUB_EVENT_NAME}"                      # "push" or "pull_request"
          PR_ACTION="${{ github.event.action }}"            # "opened" or "closed"
          TO_BRANCH="${GITHUB_REF##*/}"                     # e.g. "main"
          FROM_BRANCH=""
          if [ "$EVENT" = "pull_request" ]; then
            FROM_BRANCH="${{ github.event.pull_request.head.ref }}"
          fi

          # build JSON and POST
          curl -X POST https://<your-repl-url>/webhook \
            -H "Content-Type: application/json" \
            -d "{\"event_type\":\"$EVENT\",\
